{ user, config, pkgs, ... }:

{
  ".claude/settings.json".text = builtins.toJSON {
    permissions = {
      allow = [
        "WebFetch"
        "WebSearch"
        "Bash(git status:*)"
        "Bash(git diff:*)"
        "Bash(git log:*)"
        "Bash(git show:*)"
        "Bash(git branch:*)"
        "Bash(git remote:*)"
        "Bash(git fetch:*)"
        "Bash(git merge-base:*)"
        "Bash(git ls-tree:*)"
        "Bash(git rev-parse:*)"
        "Bash(git add:*)"
        "Bash(git checkout:*)"
        "Bash(git pull:*)"
        "Bash(git push:*)"
        "Bash(git stash:*)"
        "Bash(gh pr view:*)"
        "Bash(gh pr diff:*)"
        "Bash(gh pr list:*)"
        "Bash(gh pr checks:*)"
        "Bash(gh pr edit:*)"
        "Bash(gh run view:*)"
        "Bash(gh run list:*)"
        "Bash(gh release list:*)"
        "Bash(gh issue view:*)"
        "Bash(gh issue list:*)"
        "Bash(gh api:*)"
        "Bash(gh search:*)"
        "Bash(gh search code:*)"
        "Bash(kubectl get:*)"
        "Bash(kubectl describe:*)"
        "Bash(kubectl logs:*)"
        "Bash(kubectl config get-contexts:*)"
        "Bash(kubectl config view:*)"
        "Bash(kubectl api-resources:*)"
        "Bash(kubectl explain:*)"
        "Bash(kubectl top:*)"
        "Bash(kubectl version:*)"
        "Bash(helm lint:*)"
        "Bash(helm template:*)"
        "Bash(helm show values:*)"
        "Bash(helm pull:*)"
        "Bash(helm list:*)"
        "Bash(helm dependency build:*)"
        "Bash(argocd version:*)"
        "Bash(argocd app list:*)"
        "Bash(argocd app get:*)"
        "Bash(argocd app manifests:*)"
        "Bash(argocd app sync:*)"
        "Bash(terraform fmt:*)"
        "Bash(terraform validate:*)"
        "Bash(terraform show:*)"
        "Bash(terraform state list:*)"
        "Bash(terraform output:*)"
        "Bash(terraform plan:*)"
        "Bash(aws sts get-caller-identity:*)"
        "Bash(aws iam get-policy:*)"
        "Bash(aws iam get-policy-version:*)"
        "Bash(aws iam get-role:*)"
        "Bash(aws iam get-role-policy:*)"
        "Bash(aws iam list-attached-role-policies:*)"
        "Bash(aws iam list-role-policies:*)"
        "Bash(aws ecr describe-images:*)"
        "Bash(aws ecr describe-pull-through-cache-rules:*)"
        "Bash(aws ecr get-repository-policy:*)"
        "Bash(aws rds describe-db-instances:*)"
        "Bash(aws s3 ls:*)"
        "Bash(aws ec2 describe-instances:*)"
        "Bash(aws ec2 describe-vpcs:*)"
        "Bash(aws ec2 describe-subnets:*)"
        "Bash(aws ec2 describe-security-groups:*)"
        "Bash(aws s3 cp:*)"
        "Bash(aws secretsmanager:*)"
        "Bash(docker ps:*)"
        "Bash(docker images:*)"
        "Bash(docker logs:*)"
        "Bash(docker inspect:*)"
        "Bash(cat:*)"
        "Bash(head:*)"
        "Bash(tail:*)"
        "Bash(less:*)"
        "Bash(find:*)"
        "Bash(ls:*)"
        "Bash(tree:*)"
        "Bash(file:*)"
        "Bash(stat:*)"
        "Bash(diff:*)"
        "Bash(diffstat:*)"
        "Bash(wc:*)"
        "Bash(du:*)"
        "Bash(df:*)"
        "Bash(grep:*)"
        "Bash(sort:*)"
        "Bash(comm:*)"
        "Bash(jq:*)"
        "Bash(yq:*)"
        "Bash(xargs:*)"
        "Bash(xargs grep:*)"
        "Bash(xxd:*)"
        "Bash(dyff between:*)"
        "Bash(cp:*)"
        "Bash(mkdir:*)"
        "Bash(chmod:*)"
        "Bash(tar:*)"
        "Bash(tee:*)"
        "Bash(cd:*)"
        "Bash(pwd:*)"
        "Bash(which:*)"
        "Bash(env:*)"
        "Bash(date:*)"
        "Bash(hostname:*)"
        "Bash(whoami:*)"
        "Bash(uname:*)"
        "Bash(uptime:*)"
        "Bash(echo:*)"
        "Bash(python3:*)"
        "Bash(poetry install:*)"
        "Bash(make docs:*)"
      ];
      deny = [];
      ask = [];
    };
    enabledPlugins = {
      "pyright-lsp@claude-plugins-official" = true;
      "typescript-lsp@claude-plugins-official" = true;
      "semgrep-plugin@semgrep" = true;
      "playwright-skill@playwright-skill" = true;
    };
    alwaysThinkingEnabled = true;
  };
}